export default {
    colors: {
        default:{
            default:'zinc-500',
            black:'zinc-600',
            light:'zinc-400',
        },
        primary:{
            default:'blue-500',
            black:'blue-600',
            light:'blue-400',
        },
        secondary:{
            default:'slate-500',
            black:'slate-600',
            light:'slate-400',
        },
        success:{
            default:'green-500',
            black:'green-600',
            light:'green-400',
        },
        info:{
            default:'orange-500',
            black:'orange-600',
            light:'orange-400',
        },
        warning:{
            default:'amber-500',
            black:'amber-600',
            light:'amber-400',
        },
        danger:{
            default:'red-500',
            black:'red-600',
            light:'red-400',
        },
    }
}